version: 2.1

jobs:
  build_and_test:
    working_directory: ~/circleci
    docker: 
      - image: "fkrull/multi-python"
    steps:
      - checkout
      - run:
          name: create venv and install package dependencies
          command: | 
            tox

workflows:
  build-and-test:
    jobs:
      - build_and_test