version: 2.1

jobs:
  build_and_test:
    working_directory: ~/circleci
    docker: 
      - image: "circleci/python:3.7.9"
    steps:
      - checkout
      - run:
          name: install package dependencies in venv
          command: | 
            python3 -m venv venv 
            source venv/bin/activate
            pip3 install -r requirements.txt
      - run:
          name: activate venv and build package
          command: |
            source venv/bin/activate
            python3 setup.py install
      - run:
          name: install test dependencies and run pytest
          command: | 
            source venv/bin/activate
            pip3 install -r requirements-test.txt
            pytest --cov=pyhicrep --cov-append

workflows:
  build-and-test:
    jobs:
      - build_and_test